version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm config set registry https://registry.npmjs.org/
            - run: npm config set loglevel info
            - run: npm config set ignore-scripts true
            - run: npm install
            - run: npm audit fix --only=prod --audit-level=moderate
            - run: npm run test --if-present
workflows:
    build-and-test:
      jobs:
        - build-and-test
