# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    tags: v1.*
  pull_request:
    branches: [ master ]
    tags: v1.*

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
          npm config set registry https://registry.npmjs.org/
          npm config set loglevel info
          npm config set ignore-scripts true
          npm ci
          npm audit
      env:
        CI: true

  build:
    name: Install & Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [setup]
    
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
          npm config set ignore-scripts false
          npm run build --if-present
          npm test
      env:
        CI: true
        
  test:
    name: Unit test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [build]
    
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
          npm config set ignore-scripts false
          npm run build --if-present
          npm test
      env:
        CI: true
